package de.dorbird;

public enum LandType {
    BASIC, SNOWCOVERED, DUAL, FILTER1, FILTER2, FETCH, PAIN, SHOCK, HORIZON, CHECK, FAST, CASTLE,
    BOUNCE, TRIOME, DUALCYLCE, TRITAP, SCRYTEMPLE, FIVECOLOR, TRIBAL, TANGO, SHADOW, CREATURE,
    MONOCREATURE, SLOWFETCH, GAIN, BOND, TAINTED
}
